########################################################################
#                Laravel Docker Development Environment                 #
########################################################################
# A comprehensive Docker environment for Laravel development with      #
# multi-PHP support, MySQL, Redis, Nginx, and development tools       #
########################################################################

########################################################################
#                      SHARED CONFIGURATION                            #
########################################################################
x-app-args: &default-args
  USER_NAME: ${USER_NAME:-docker}
  USER_GROUP: ${USER_GROUP:-docker}
  USER_PASSWORD: ${USER_PASSWORD:-docker}
  ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
  USER_GID: ${USER_GID:-1000}
  USER_UID: ${USER_UID:-1000}
  DESTINATION_DIR: ${DESTINATION_DIR:-/var/www}
  WORKSPACE_SSH_PORT: ${WORKSPACE_SSH_PORT:-2222}

x-common-volumes: &common-volumes
  - app-data:${DESTINATION_DIR:-/var/www}:rw
  - ./sitesMap.yaml:/etc/nginx/sitesMap.yaml:ro

x-network: &default-network
  networks:
    - laravel-docker-devenv-network

services:
  ########################################################################
  #                      WORKSPACE CONTAINER                             #
  ########################################################################
  workspace:
    build:
      context: ./
      dockerfile: docker/workspace.Dockerfile
      args:
        <<: *default-args
    container_name: workspace
    restart: unless-stopped
    hostname: workspace
    volumes:
      - app-data:${DESTINATION_DIR}:rw
      - ./docker/supervisor/conf.d:/etc/supervisor/conf.d:rw
      - ./docker/scripts/workspace.entrypoint.sh:/entrypoint.sh:ro
    working_dir: ${DESTINATION_DIR}
    <<: *default-network
    environment:
      - TZ=${TZ}
      - USER_NAME=${USER_NAME:-docker}
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - DESTINATION_DIR=${DESTINATION_DIR:-/var/www}
    ports:
      - "${WORKSPACE_SSH_PORT:-2222}:${WORKSPACE_SSH_PORT:-2222}"  # SSH
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    healthcheck:
      test: ["CMD", "php", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

########################################################################
#                      NETWORKS                                        #
########################################################################
networks:
  laravel-docker-devenv-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET:-"172.19.0.0/16"}

########################################################################
#                      VOLUMES                                         #
########################################################################
volumes:
  # Application data volume
  app-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DIR}
